# 生產環境配置
app:
  # 生產環境資料庫配置 - 強制從環境變數讀取  
  database:
    host: ${DB_HOST}  # 強制從環境變數讀取，無預設值
    port: ${DB_PORT}
    name: ${DB_NAME:springboot_template_db_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 生產環境 CORS 配置 - 更嚴格的安全設定
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}  # 強制從環境變數讀取，不提供預設值
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE}  # 移除 OPTIONS
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept}  # 更嚴格的標頭限制
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}  # 生產環境預設關閉憑證
    max-age: ${CORS_MAX_AGE:1800}  # 更短的快取時間

  # 生產環境快取配置 - 更大的快取和更長的過期時間
  cache:
    type: caffeine
    spec: ${CACHE_SPEC:maximumSize=10000,expireAfterAccess=1800s,expireAfterWrite=900s}

spring:
  # 生產環境資料庫連接池優化
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      leak-detection-threshold: 60000
      max-lifetime: 1800000
      validation-timeout: 5000
      pool-name: "HikariCP-Production"
  
  jpa:
    hibernate:
      ddl-auto: validate  # 生產環境只驗證，不自動修改 schema
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC

  # 生產環境 Flyway 設定 - 更嚴格的驗證
  flyway:
    enabled: true
    baseline-on-migrate: false  # 生產環境不允許自動 baseline
    validate-on-migrate: true
    out-of-order: false         # 不允許亂序遷移
    clean-disabled: true        # 禁用 clean 操作以防意外數據丟失

# 生產環境日誌設定
logging:
  level:
    com.nicenpc: INFO
    root: INFO
    org.hibernate.SQL: WARN

# 生產環境服務器設定
server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10

# 生產環境監控 - 僅暴露必要端點
management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health,info  # 僅暴露必要端點，提高安全性
