-- V2__Restructure_users_table.sql
-- 重構使用者資料表以符合編碼標準

-- 創建新的使用者資料表
CREATE TABLE IF NOT EXISTS TB_USER_NEW (
    USER_ID BIGSERIAL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL,
    CREATED_BY BIGINT NOT NULL DEFAULT 1,
    UPDATED_AT TIMESTAMPTZ DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL,
    UPDATED_BY BIGINT NOT NULL DEFAULT 1,
    VERSION INTEGER DEFAULT 0 NOT NULL
);

-- 遷移現有資料
INSERT INTO TB_USER_NEW (USER_NAME, USER_EMAIL, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VERSION)
SELECT name, email, true, 
       COALESCE(created_at AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
       1,
       COALESCE(updated_at AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
       1,
       0
FROM users;

-- 刪除舊表
DROP TABLE IF EXISTS users CASCADE;

-- 重新命名新表
ALTER TABLE TB_USER_NEW RENAME TO TB_USER;

-- 建立索引以提升查詢效能
CREATE INDEX IF NOT EXISTS IDX_TB_USER_USER_EMAIL ON TB_USER(USER_EMAIL);
CREATE INDEX IF NOT EXISTS IDX_TB_USER_USER_NAME ON TB_USER(USER_NAME);
CREATE INDEX IF NOT EXISTS IDX_TB_USER_IS_ACTIVE ON TB_USER(IS_ACTIVE);

-- 建立更新時間觸發器的函數
CREATE OR REPLACE FUNCTION update_tb_user_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = (NOW() AT TIME ZONE 'UTC');
    NEW.VERSION = OLD.VERSION + 1;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 建立觸發器來自動更新 UPDATED_AT 欄位
DROP TRIGGER IF EXISTS update_tb_user_updated_at ON TB_USER;
CREATE TRIGGER update_tb_user_updated_at
    BEFORE UPDATE ON TB_USER
    FOR EACH ROW
    EXECUTE FUNCTION update_tb_user_updated_at_column();

-- 添加表和欄位註釋
COMMENT ON TABLE TB_USER IS '使用者資料表';
COMMENT ON COLUMN TB_USER.USER_ID IS '使用者唯一識別碼';
COMMENT ON COLUMN TB_USER.USER_NAME IS '使用者姓名';
COMMENT ON COLUMN TB_USER.USER_EMAIL IS '使用者電子郵件地址';
COMMENT ON COLUMN TB_USER.IS_ACTIVE IS '是否啟用狀態';
COMMENT ON COLUMN TB_USER.CREATED_AT IS '資料建立時間（UTC+0）';
COMMENT ON COLUMN TB_USER.CREATED_BY IS '資料建立者ID';
COMMENT ON COLUMN TB_USER.UPDATED_AT IS '資料最後更新時間（UTC+0）';
COMMENT ON COLUMN TB_USER.UPDATED_BY IS '資料最後更新者ID';
COMMENT ON COLUMN TB_USER.VERSION IS '樂觀鎖版本號';
